### PR TITLE
Improve readability of bitcoinbinary.org

### PR DESCRIPTION
**Pull request by RequestPrivacy**
The current index.html file lists all contributed builds chronological. Although it looks nice, it could become difficult to find the application one wishes to verify/compare the own build to. Therefore an application specific sorting is proposed. An alphabetical one prevents any particular bias towards a specific application.

### CODE REVIEW

**Comment by nvk** [comment]
More versions of the same software will come, so log/chrono format makes more sense. In the future we can add sorting. Could also bold the project name.

**Comment by RequestPrivacy** [comment]
Exactly, more versions of the same software will come and hopefully a lot more build verifications. So it makes no sense to throw them all into a time chronological order like it's done currently. Or maybe I'm off and don't understand the current sorting order?

This format:
Screenshot-20210922134354-1168x360

seems much more approachable like the current one:
Screenshot-20210922135255-1187x262

Also, version numbering and therefore line length is rather application specific so although the more compact formatting rn seems pleasing, as number of verifications increase, formatting no. 1 wins imho.

**Comment by nvk** [comment]
The issue with your proposed format is that it will push other projects much further below as entry count increases.

We could make an incremental change to increase visibility by bolding the project name in the inline entry.

**Comment by RequestPrivacy** [comment]
Ah, now I understand your concern - thanks for clarifying. That's indeed a thing to consider, although I'm not quite sure what's more annoying: searching for the latest contribution in a big block full of densely written lines of links or scrolling the page to a single small headline with the application name.

Bolding the name inline wouldn't be my favourite solution as it generates more "aesthetically unrest". So lets keep the pull request closed and see how the reactions are in the future.

**Pull request closed without merging**
