### PR TITLE
multiple-projects/artifacts.sh: bump more versions

### PR DESCRIPTION
**Pull request by RandyMcMillan**
multiple-projects/artifacts.sh: bump more versions

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
don't merge yet!

**Comment by RandyMcMillan** [comment]
my branch CI: [https://github.com/bitcoincore-dev/.github/actions/runs/3896234348](https://github.com/bitcoincore-dev/.github/actions/runs/3896234348)

**Comment by RandyMcMillan** [comment]
I just realized i can use these commits for testing my nostr integration...

so dont merge!!

**Comment by caheredia** [comment]
@RandyMcMillan what are you working on? Anything I can help with?

**Pull request closed without merging**
