### PR TITLE
speedup_video.py fix

### PR DESCRIPTION
**Pull request by scgbckbone**
* end segment can be string "end" --> handle this corner case

### CODE REVIEW

**Comment by fiatjaf** [comment]
I've hit what seems to be the same bug being fixed here myself a couple times while testing.

**Comment by nvk** [comment]
Push to branch main
[7](https://github.com/coinkite/bitcoinbinary.org/actions/runs/3309015492/jobs/5461822124#step:5:8)
Pushing to https://github.com/coinkite/bitcoinbinary.org.git
[8](https://github.com/coinkite/bitcoinbinary.org/actions/runs/3309015492/jobs/5461822124#step:5:9)
error: atomic push failed for ref refs/heads/main. status: 5
[9](https://github.com/coinkite/bitcoinbinary.org/actions/runs/3309015492/jobs/5461822124#step:5:10)

[10](https://github.com/coinkite/bitcoinbinary.org/actions/runs/3309015492/jobs/5461822124#step:5:11)
fatal: protocol error: bad line length character: erro
[11](https://github.com/coinkite/bitcoinbinary.org/actions/runs/3309015492/jobs/5461822124#step:5:12)
To https://github.com/coinkite/bitcoinbinary.org.git
[12](https://github.com/coinkite/bitcoinbinary.org/actions/runs/3309015492/jobs/5461822124#step:5:13)
 ! [rejected]        HEAD -> main (fetch first)
[13](https://github.com/coinkite/bitcoinbinary.org/actions/runs/3309015492/jobs/5461822124#step:5:14)
error: failed to push some refs to 'https://github.com/coinkite/bitcoinbinary.org.git'
[14](https://github.com/coinkite/bitcoinbinary.org/actions/runs/3309015492/jobs/5461822124#step:5:15)
hint: Updates were rejected because the remote contains work that you do
[15](https://github.com/coinkite/bitcoinbinary.org/actions/runs/3309015492/jobs/5461822124#step:5:16)
hint: not have locally. This is usually caused by another repository pushing
[16](https://github.com/coinkite/bitcoinbinary.org/actions/runs/3309015492/jobs/5461822124#step:5:17)
hint: to the same ref. You may want to first integrate the remote changes
[17](https://github.com/coinkite/bitcoinbinary.org/actions/runs/3309015492/jobs/5461822124#step:5:18)
hint: (e.g., 'git pull ...') before pushing again.
[18](https://github.com/coinkite/bitcoinbinary.org/actions/runs/3309015492/jobs/5461822124#step:5:19)
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
[19](https://github.com/coinkite/bitcoinbinary.org/actions/runs/3309015492/jobs/5461822124#step:5:20)
Error: Invalid exit code: 1
[20](https://github.com/coinkite/bitcoinbinary.org/actions/runs/3309015492/jobs/5461822124#step:5:21)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
[21](https://github.com/coinkite/bitcoinbinary.org/actions/runs/3309015492/jobs/5461822124#step:5:22)
    at ChildProcess.emit (node:events:390:28)
[22](https://github.com/coinkite/bitcoinbinary.org/actions/runs/3309015492/jobs/5461822124#step:5:23)
    at maybeClose (node:internal/child_process:1064:16)
[23](https://github.com/coinkite/bitcoinbinary.org/actions/runs/3309015492/jobs/5461822124#step:5:24)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
[24](https://github.com/coinkite/bitcoinbinary.org/actions/runs/3309015492/jobs/5461822124#step:5:25)
  code: 1
[25](https://github.com/coinkite/bitcoinbinary.org/actions/runs/3309015492/jobs/5461822124#step:5:26)
}
[26](https://github.com/coinkite/bitcoinbinary.org/actions/runs/3309015492/jobs/5461822124#step:5:27)
Error: Invalid exit code: 1
[27](https://github.com/coinkite/bitcoinbinary.org/actions/runs/3309015492/jobs/5461822124#step:5:28)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
[28](https://github.com/coinkite/bitcoinbinary.org/actions/runs/3309015492/jobs/5461822124#step:5:29)
    at ChildProcess.emit (node:events:390:28)
[29](https://github.com/coinkite/bitcoinbinary.org/actions/runs/3309015492/jobs/5461822124#step:5:30)
    at maybeClose (node:internal/child_process:1064:16)
[30](https://github.com/coinkite/bitcoinbinary.org/actions/runs/3309015492/jobs/5461822124#step:5:31)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)


Still won’t build. Instead of debugging GitHub actions, I might move this to a real place. And/or have people commit their own videos. While automation happens outside GH cluster…

**Comment by fiatjaf** [comment]
I think this just happened because you merged two PRs in rapid sucession so when the build action tried to commit its generated assets the repo had moved.

**Comment by nvk** [comment]
I tried again, seems to have rebuild.

**Pull request merged**
